spring.application.name=rosterforge

# --- HashiCorp Vault ---
spring.config.import=vault://
spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.token=root
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=rosterforge
spring.cloud.vault.fail-fast=true

spring.datasource.url=jdbc:postgresql://localhost:5434/rosterforge
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=localhost:9094